# SPDX-FileCopyrightText: StorPool <support@storpool.com>
# SPDX-License-Identifier: BSD-2-Clause

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - toc.follow
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
site_name: pve-storpool
repo_url: https://github.com/ppenchev-storpool/pve-storpool
repo_name: pve-storpool
site_author: ppentchev-storpool
site_url: https://repo.storpool.com/public/doc/pve/pve-storpool
site_dir: site/docs
nav:
  - 'index.md'
  - 'Data format definitions': 'data.md'
  - 'To-do list': 'todo.md'
markdown_extensions:
  - toc:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
# plugins:
#   - mkdocstrings:
#       default_handler: python
#       handlers:
#         python:
#           paths: [src]
#           options:
#             heading_level: 3
#             show_root_heading: true
#   - search
# watch:
#   - 'src/parse_stages'
